Repository openshift-eng/ocp-qe-perfscale-ci, pull requests merged in 2024-06, with the labels that each got.

#605 Fix metric promql: Bps measured by netobserv
  scripts/queries/netobserv_prometheus_queries.yaml
Labels: lgtm, approved, ok-to-test

#604 NETOBSERV-1677 - updates
  Jenkinsfile
  scripts/netobserv.sh
  scripts/netobserv/flows_v1beta2_flowcollector.yaml
Labels: lgtm, approved

#606 NETOBSERV-1694 metrics and fixing kafkaTopic delete issue
  scripts/README.md
  scripts/netobserv.sh
  scripts/netobserv/flows_v1beta2_flowcollector.yaml
  scripts/queries/netobserv_prometheus_queries.yaml
  scripts/queries/netobserv_touchstone_statistics_config.json
  scripts/queries/netobserv_touchstone_tolerancy_config.json
Labels: lgtm, approved

#608 archive artifacts
  Jenkinsfile
  scripts/netobserv.sh
Labels: lgtm, approved

#609 use kafka by default for perf tests
  scripts/netobserv/flows_v1beta2_flowcollector.yaml
Labels: lgtm, approved

#610 use numpy < 2.0.0
  scripts/requirements.txt
Labels: lgtm, approved

#611 remove kafkaBatchSize
  scripts/netobserv/flows_v1beta2_flowcollector.yaml
Labels: lgtm, approved, do-not-merge/hold

#612 workaround for numpy
  Jenkinsfile
Labels: lgtm, approved

#613 flp loglevel to info
  scripts/netobserv/flows_v1beta2_flowcollector.yaml
Labels: lgtm, approved

#614 Ocm api load Job
  Jenkinsfile
  OWNERS
  README.md
  config/benchmarks/empty.json
  config/benchmarks/ocm.json
  scripts/cleanup_clusters.sh
  scripts/run_ocm_api_load.sh
  scripts/run_ocm_benchmark.sh
Labels: lgtm, needs-ok-to-test, do-not-merge/invalid-owners-file
