Repository openshift-eng/ocp-qe-perfscale-ci, pull requests merged in 2025-03, with the labels that each got.

#696 adding script to update outboudn ports on azure
  az_outbound_ports.sh
Labels: lgtm, approved

#700 Update perfscale repo
  prow/generate_jobs_in_gsheet/get_periodic_jobs.py
Labels: lgtm, approved

#698 adding new org name
  Jenkinsfile
Labels: lgtm, approved

#697 Post results to es
  Jenkinsfile
Labels: lgtm

#699 Adding arch_type
  upgrade_scripts/upgrade.sh
Labels: lgtm, approved

#702 Update repo links
  Jenkinsfile
  help_find_flexy_uuid.py
  post_uuid_to_es.py
Labels: lgtm, approved

#703 Update flexy URL
  help_find_flexy_uuid.py
  post_uuid_to_es.py
Labels: lgtm

#705 update owners
  OWNERS
Labels: lgtm, approved

#706 NETOBSERV-2128 use AWS_DEFAULT_REGION if already set and retries for s3 deletion
  scripts/deploy-loki-aws-secret.sh
  scripts/netobserv.sh
Labels: lgtm, approved

#707 Not using the highest version on numpy
  requirements.txt
Labels: lgtm, approved

#616 Ocm api load
  Jenkinsfile
  scripts/run_ocm_api_load.sh
  scripts/run_ocm_benchmark.sh
Labels: lgtm, approved, needs-ok-to-test

#708 Get rid of infinite loops, exit and use tmp in nope.py
  scripts/amq-streams/default.yaml
  scripts/amq-streams/metrics-config.yaml
  scripts/netobserv.sh
  scripts/nope.py
Labels: lgtm, approved
